# Домашняя работа №1

1. Импорт библиотеки NumPy с общепринятым сокращением.
2. Примеры создания массивов:
   - из обычных списков;
   - с использованием функций `zeros`, `ones`, `arange` или аналогичных.
3. Демонстрация атрибутов:
   - вывод формы (shape) и типа данных (dtype) для одного из массивов.
4. Примеры индексирования и срезов:
   - получение отдельного элемента;
   - извлечение подмассива с помощью среза.
5. Примеры векторных операций и базовых статистик:
   - поэлементное сложение или умножение массивов;
   - вычисление средней величины (`mean`) или другой простой статистики.

## 1. Импорт библиотеки NumPy с общепринятым сокращением.

In [171]:
import numpy as np

## 2. Примеры создания массивов:

###  из обычных списков

In [172]:
array_from_list = np.array([1, 2, 3, 4])
print("Массив из списка:", array_from_list)

Массив из списка: [1 2 3 4]


### C использованием функций `zeros`, `ones`, `arange` или аналогичных.

In [173]:
array_zeros = np.zeros(4)
print("Массив из нулей:", array_zeros)

array_ones = np.ones(4)
print("Массив из единиц:", array_ones)

array_range = np.arange(10, 20, 2)
print("Массив с arange:", array_range)

Массив из нулей: [0. 0. 0. 0.]
Массив из единиц: [1. 1. 1. 1.]
Массив с arange: [10 12 14 16 18]


## 3. Демонстрация атрибутов:

###     Bывод формы (shape) и типа данных (dtype) для одного из массивов.

In [174]:
print("Форма массива (shape):", array_from_list.shape)
print("Тип данных (dtype):", array_from_list.dtype)

Форма массива (shape): (4,)
Тип данных (dtype): int64


## 4. Примеры индексирования и срезов:

### Получение отдельного элемента;


In [175]:
print("Элемент с индексом 2:", array_from_list[2])

Элемент с индексом 2: 3


### Извлечение подмассива с помощью среза.

In [176]:
sub_array = array_from_list[1:4]
print("Подмассив с 1 по 3 индекс:", sub_array)

Подмассив с 1 по 3 индекс: [2 3 4]


## 5. Примеры векторных операций и базовых статистик:

### Поэлементное сложение или умножение массивов;

In [177]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

summa = a + b
proizvedenie = a * b

print("Сложение массивов:", summa)
print("Умножение массивов:", proizvedenie)

Сложение массивов: [5 7 9]
Умножение массивов: [ 4 10 18]


### Вычисление средней величины (`mean`) или другой простой статистики.

In [178]:
mean_value = np.mean(a)
print("Среднее значение массива a:", mean_value)

Среднее значение массива a: 2.0


## Двумерный массив

In [179]:
arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("Двумерный массив:\n", arr_2d)

Двумерный массив:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Создание двумерного массива из нулей

In [180]:
arr2d_zeros = np.zeros((2, 3))
print("Двумерный массив из нулей:\n", arr2d_zeros)

Двумерный массив из нулей:
 [[0. 0. 0.]
 [0. 0. 0.]]


## Получение отдельного элемента двумерного массива

In [181]:
element = arr_2d[1, 2]  # строка 1, столбец 2
print("Элемент [1,2] двумерного массива:", element)

Элемент [1,2] двумерного массива: 8


## Срез двумерного массива (вторая строка)


In [182]:
row = arr_2d[1, :]
print("Вторая строка двумерного массива:", row)

Вторая строка двумерного массива: [ 6  7  8  9 10]



## Срез двумерного массива (первые две строки, столбцы 1–2)


In [183]:
sub = arr_2d[0:2, 1:3]
print("Подмассив [0:2, 1:3]:\n", sub)

Подмассив [0:2, 1:3]:
 [[2 3]
 [7 8]]


## Поэлементное сложение двумерных массивов


In [184]:
arr_2d_2 = np.array([[7, 8, 9, 10 , 11], [12, 13, 14, 15, 16]])
sum_2d = arr_2d + arr_2d_2
print("Сложение двумерных массивов:\n", sum_2d)

Сложение двумерных массивов:
 [[ 8 10 12 14 16]
 [18 20 22 24 26]]


## Среднее значение по всем элементам двумерного массива


In [185]:
mean_2d = np.mean(arr_2d)
print("Среднее значение двумерного массива:", mean_2d)


Среднее значение двумерного массива: 5.5



## Сумма по столбцам (по оси 0)


In [186]:
col_sum = np.sum(arr_2d, axis=0)
print("Сумма по столбцам:", col_sum)

Сумма по столбцам: [ 7  9 11 13 15]
